# you can disable lines of this config by commenting them out by placing a '#' at the start of the line
hwdec=auto-safe

# set audio and subtitle language to Japanese.
alang=jpn,jp,ja
slang=jpn,jp,ja
# you can change target language by editing jpn,jp,ja to other language codes: e.g. for Korean: kor,kr,ko

# you can press 'v' to toggle subtitles (to watch raw)
# uncomment this to disable subtitles by default
# sid=no

autocreate-playlist=same
audio-display=no
# fs=yes

osd-bar=no

